### PR TITLE
Add minimum Euslisp interface to baxterlgv7

### PR DESCRIPTION
**Pull request by pazeshun**
## What I did
1. Make `baxterlgv7.l` and `baxterlgv7-interface.l` by copying `baxter.l` and `baxter-interface.l`
2. Enable to move left gripper_v7
    - Change file name in `require`
    - Change class name
    - Fix how to move fingers because each finger of left gripper_v7 model has 3 joints (previous: 2 joints).
    - In order to move `*baxter*` realistically, I added some trick in `:hand-grasp-pose` as 2 joints out of 3 don't move separately.
3. Fix `:start-grasp` and `:stop-grasp` to move in left gripper_v7

## What I haven't finished
- Move whole baxterlgv7
- Add moveit config of baxterlgv7

### CODE REVIEW

**Comment by knorth55** [comment]
it looks your code is correct, but i could not check it.
Can you add test code?
Or can you add video that proves these code can surely moves your gripper?

**Comment by pazeshun** [comment]
Sorry for lacking test code.
I'll make test code checking following
- Generation of `*baxter*` and `*ri*`
- Finger movement in :hand-grasp-pre-pose and :hand-grasp-pose

Thank you for nice suggestion about video.
I'll take video proving `*ri*` function.

**Comment by pazeshun** [comment]
Add test code.
Other minor fix: Add baxter-interface test to CMakeLists.txt (lacking in #2500)

**Comment by pazeshun** [comment]
- Remove `:speak` test
  - Because `:speak` is defined and tested in `pr2eus` (https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/318, https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/332)
  - If we want to pass this test, we need to use `pr2eus` from source in travis as the change above is not released.
- Add `:move-hand` test instead

**Comment by pazeshun** [comment]
Test passed.
@knorth55 Currently I can't take video because new gripper is broken and fixing takes time.
Please approve this PR if you feel ok for lacking video.

**Comment by pazeshun** [comment]
Thanks!

**Pull request merged**
