### PR TITLE
update baxter_common repo in fc.rosinstall

### PR DESCRIPTION
**Pull request by knorth55**
this repo is for jsk_apc.
Make collision head smaller than before.
It makes moveit to solve path successfully.

### CODE REVIEW

**Comment by pazeshun** [comment]
+1
But I think we had better solve this problem by settings in move-it

**Comment by knorth55** [comment]
collision head in `baxter_description` is too big and already malformed.
In moveit, it can ignore collision of `collision head`, but i thought it is better to make them smaller.
collision_head

**Comment by pazeshun** [comment]
What kind of path can move-it solve thanks to this PR?
Could you  paste screenshot?

**Comment by knorth55** [comment]
ik-bin-entrance :b

**Comment by pazeshun** [comment]
I understood. Thanks

**Comment by knorth55** [comment]
please merge this

**Pull request merged**
