### PR TITLE
[jsk_2016_01_baxter_apc] Merge gripper-v2

### LINKED ISSUE #1455: [jsk_2016_01_baxter_apc] Merge gripper-v2 into master
Now gripper-v2 branch is ready to be merged.
How about master? It's ready to be merged gripper-v2 into? @knorth55 , @yuyu2172 , @wkentaro 
If It's ready, I'll make PR.

### PR DESCRIPTION
**Pull request by pazeshun**
Closes #1455 
I'll test this in real robot.
Please tell me how to run SIB.

### CODE REVIEW

**Comment by pazeshun** [comment]
Now I realize that right arm can't pass test-ik-in-bin because IK of right arm comes not to move gripper servo.
@knorth55 Is the whole region this test examines needed? Can't we narrow it? Or we should test with two target coordinates(one is z up and x forward, the other is x up and z backward) to bring out the performance of the right gripper

**Comment by pazeshun** [comment]
I changed test-ik-in-bin to test with two target coordinates.

**Comment by pazeshun** [comment]
Without #1518 , we can't move the right arm of the real robot.
So please merge #1518

**Comment by knorth55** [comment]
you mean you will close this PR?

**Comment by pazeshun** [comment]
I think the status of this PR will automatically change to "Merged" when #1518 is merged.
If not, I will close this PR

**Comment by k-okada** [comment]
can I merge this ? @pazeshun

**Comment by pazeshun** [comment]
@k-okada Please wait

**Comment by pazeshun** [comment]
Fixed the point mentioned by @knorth55 in #1518

**Comment by pazeshun** [comment]
@k-okada I think we should merge #1518

**Comment by k-okada** [comment]
#1518 will be reverted in the future, so I think we should merge this one , then merge #1518 which only contains https://github.com/start-jsk/jsk_apc/pull/1518/commits/3b734ca213b71beaad0df4d8038b4cdc72f9ede8

**Comment by pazeshun** [comment]
@k-okada Thank you for comment
@knorth55 Please check this, too.

**Comment by knorth55** [comment]
+1

**Pull request merged**
