### PR TITLE
Bin shelf model

### PR DESCRIPTION
**Pull request by pazeshun**
From #1611 
~~I included the commit of #1633 for easy test. When test ends, I'll erase this commit.
After I fix `FIXME` in the last commit, I'll erase WIP tag.~~
FIXME is fixed and no more exist. I erased WIP.

### CODE REVIEW

**Comment by pazeshun** [comment]
Fixes #1640 in the last commit.
After this PR, please run `roslaunch jsk_2016_01_baxter_apc setup_head.launch` in doura.

**Comment by wkentaro** [comment]
Hey please remove my commit.

**Comment by pazeshun** [comment]
For now, the bag file used in `test_move_arm_to_bin.test` is old bounding box array.
Also, we need `/bin_atof_clipper/prefixes` and `/bin_gtol_clipper/prefixes` to know the order of bounding box array, but these parameters aren't defined in `test_move_arm_to_bin.test`

For now, I disabled `test_move_arm_to_bin.test` in the last commit.
I'll make another PR to fix these after this PR is merged.

**Comment by pazeshun** [comment]
rebase origin/master

**Comment by pazeshun** [comment]
@yuyu2172 Please use this PR.

**Comment by knorth55** [comment]
👍

**Comment by pazeshun** [comment]
@knorth55 Sorry, I added a new commit to get readable error when robot is unable to get parameter. Please also review this.

**Comment by knorth55** [comment]
👍

**Comment by pazeshun** [comment]
I'm so sorry.... I have bug in the last commit....

**Comment by pazeshun** [comment]
Fixed.
@knorth55 Please review this. I'm sorry.

**Comment by knorth55** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Pull request merged**
