### PR TITLE
set nil not to initialize default moveit config in baxter-interface

### PR DESCRIPTION
**Pull request by knorth55**
Requires https://github.com/jsk-ros-pkg/jsk_robot/pull/719

### CODE REVIEW

**Comment by knorth55** [comment]
in order to use our custom vacuum gripper, we need to set own moveit-environment like https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L257-L319

**Comment by pazeshun** [comment]
This needs jsk-ros-pkg/jsk_robot#719

**Comment by knorth55** [comment]
i wroted

**Comment by pazeshun** [comment]
I understood. Just in case

**Comment by knorth55** [comment]
upstream merged https://github.com/jsk-ros-pkg/jsk_robot/pull/719

**Comment by pazeshun** [comment]
+1

**Comment by knorth55** [comment]
please merge this

**Comment by knorth55** [comment]
@wkentaro please merge this

**Pull request merged**
