### PR TITLE
[2016apc] add JSON parse program in world.erb file

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by knorth55** [comment]
#1043

**Comment by wkentaro** [comment]
Anyone who can verify this?

@knorth55 Are there any demo picture?

**Comment by knorth55** [comment]
demo picture
screenshot from 2016-02-12 13 45 52

**Comment by knorth55** [comment]
After #1047 is merged, i will apply and make commits for #1047.
please wait merging this.

**Pull request closed without merging**
