### PR TITLE
[WIP] Use end-coords-interpolation in picking

### PR DESCRIPTION
**Pull request by pazeshun**
cc @k-okada

### CODE REVIEW

**Comment by pazeshun** [comment]
For #2379

**Comment by k-okada** [comment]
if this works, it's ok
```
25.irteusgl$ (send-message *baxter* (send *baxter* :super) :larm :inverse-kinematics (make-coords :pos #f(0 0 0)))
; failed for normal ik, starting from relaxed position
; failed for normal ik, try to move arms very slowly
; failed for slow ik, try to start from prepared poses
; starting from prepared pose ':untuck-pose'
nil
26.irteusgl$ (send-message *baxter* (send *baxter* :super) :inverse-kinematics (make-coords :pos #f(0 0 0)) :move-target (send *baxter* :larm :end-coords))
;; inverse-kinematics failed.
;; dif-pos : #f(34.952 19.6433 11.4984)/(41.7099/1)
;; dif-rot : #f(-0.004118 -0.032788 0.204916)/(0.207564/0.017453)
;;  coords : #<coordinates #X5264f30  0.0 0.0 0.0 / 0.0 0.0 0.0>
;;  angles : (0.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 -20.0 -25.0 40.0 60.0 20.0 80.0 0.0)
```

**Comment by pazeshun** [comment]
@k-okada This PR doesn't work.
because I can't set `ik-prepared-poses` as `nil` in https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-util.l#L4
What should I do?

**Comment by pazeshun** [comment]
Tested with real robot, but I have a concern about IK in `end-coords-interpolation`

**Comment by k-okada** [comment]
how about this?

BUT IF I SEE THIS CODE, I'LL REJECT, THIS IS TOO DANGEROUS.

```
(if (not (boundp '*baxter*))
    (setq *baxter* (instance baxter-robot :init)))
(if (not (boundp '*ri*))
    (setq *ri* (instance baxter-interface :init)))
(objects (list *baxter*))
(send *baxter* :reset-pose)
(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(750 0 0)))
(objects (list *baxter*))
(send *ri* :angle-vector (send *baxter* :angle-vector) 1000)
(send *ri* :wait-interpolation)
(print "ok")
(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(1000 0 800)))
(unless (assoc :inverse-kinematics-org (send baxter-robot :methods))
  (rplaca (assoc :inverse-kinematics (send baxter-robot :methods)) :inverse-kinematics-org))
;; back go original ik
(defmethod baxter-robot (:inverse-kinematics (&rest args) (print "ok")(send-super* :inverse-kinematics args)))
(print "go")
(send *ri* :angle-vector-raw (send *baxter* :angle-vector) 3000
      (*ri* . controller-type) 0 :end-coords-interpolation t)
(send *ri* :wait-interpolation)
(defmethod baxter-robot (:inverse-kinematics (&rest args) (print "ok")(send* self :inverse-kinematics-org args)))
;; restore
(print "check if back to prep-pose ik")
(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(1200 0 800)))
```
see full test code at https://gist.github.com/k-okada/5aa8bc91f2a1fb1393fdfa4559077ddd

**Comment by k-okada** [comment]
Another implementation, seems better then before, but still VERY DANGEROUS!!!

```
(if (not (boundp '*baxter*))
    (setq *baxter* (instance baxter-robot :init)))
(if (not (boundp '*ri*))
    (setq *ri* (instance baxter-interface :init)))
(objects (list *baxter*))
(send *baxter* :reset-pose)
(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(750 0 0)))
(objects (list *baxter*))
(send *ri* :angle-vector (send *baxter* :angle-vector) 1000)
(send *ri* :wait-interpolation)
(print "ok")
(defmethod baxter-robot
  (:ik-prepared-poses
   (&optional (poses :null))
   (let ((ik-prepared-poses (or (get self :ik-prepared-poses) '(:untuck-pose))))
     (cond ((eq poses :null)
            (return-from :ik-prepared-poses (if (eq ik-prepared-poses :null) nil ik-prepared-poses)))
           ((eq poses nil)

            (setf (get self :ik-prepared-poses) :null)
            (return-from :ik-prepared-poses nil))
           (t
            (setf (get self :ik-prepared-poses) poses)
            (return-from :ik-prepared-poses poses))
           ))) ;; defmethod                                                                                                            
  )

(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(1000 0 800)))
(setq hoge (send (send *ri* :robot) :ik-prepared-poses)) ;; store current poses                                                        
(send (send *ri* :robot) :ik-prepared-poses nil) ;; clear                                                                              
(print (list 'prepared-pose (send (send *ri* :robot) :ik-prepared-poses))) ;; check prepared pose                                      
(print "go")
(send *ri* :angle-vector-raw (send *baxter* :angle-vector) 3000
      (*ri* . controller-type) 0 :end-coords-interpolation t)
(send *ri* :wait-interpolation)
(send (send *ri* :robot) :ik-prepared-poses hoge) ;; restore                                                                           
(print (list 'prepared-pose (send (send *ri* :robot) :ik-prepared-poses))) ;; check prepared pose                                      
(print "check if back to prep-pose ik")
(send *baxter* :larm :inverse-kinematics (make-coords :pos #f(1200 0 800)))
```

**Comment by pazeshun** [comment]
Back to WIP

**Comment by wkentaro** [comment]
@pazeshun Is that possible to include this to 4.1.0? It should be by the next Monday.

**Comment by pazeshun** [comment]
This PR may be too unstable to use in real task, but anyway I'll do enough test tomorrow about this PR.

**Comment by pazeshun** [comment]
Move to #2533

**Comment by pazeshun** [comment]
@k-okada Your code about `:ik-prepared-poses` is moved to https://github.com/jsk-ros-pkg/jsk_robot/pull/813

**Pull request closed without merging**
