### PR TITLE
Apply stereo camera to setup_for_pick/stow.launch

### PR DESCRIPTION
**Pull request by YutoUchimi**
Enable using stereo in setup_for_pick.launch and setup_for_stow.launch.
Set argument "stereo" as "true" in default.

### CODE REVIEW

**Comment by YutoUchimi** [comment]
Videos
------

- FCN with /*_hand_camera/left/rgb/image_rect_color
fcn_with_left_rgb

- FCN with /*_hand_camera/fused/rgb/image_rect_color
fcn_with_fused_rgb

**Comment by YutoUchimi** [comment]
In this PR, I use `/*_hand_camera/fused/rgb/image_rect_color` as FCN input.
Should we use `/*_hand_camera/left/rgb/image_rect_color`?

**Comment by knorth55** [comment]
>In this PR, I use /*_hand_camera/fused/rgb/image_rect_color as FCN input.
Should we use /*_hand_camera/left/rgb/image_rect_color?

I think you are right.

**Comment by YutoUchimi** [comment]
@wkentaro 
Could you please merge this?

**Pull request merged**
