### PR TITLE
Don't rotate objects in Bin

### PR DESCRIPTION
**Pull request by pazeshun**
I'll test this in real robot

### CODE REVIEW

**Comment by ban-masa** [comment]
+1

**Comment by pazeshun** [comment]
Updated because I found that following deleted section lowers gripper to pull out it:
```
(send *baxter* arm :move-end-pos
                     (float-vector
                       0 0 (gethash :offset-avoid-bin-top _hard-coded-variables))
                     )
```
@ban-masa Please review again. Sorry.

**Comment by pazeshun** [comment]
Updated again to pull out objects sufficiently.
I removed WIP tag because it is tested in real robot.
@ban-masa Please review.

**Comment by ban-masa** [comment]
+1

**Pull request merged**
