### PR TITLE
fix failing remove gripper link from link-list, (member 'string' list…

### PR DESCRIPTION
**Pull request by k-okada**
…) requries (member 'string' list #'equal)

### CODE REVIEW

**Comment by k-okada** [comment]
https://github.com/start-jsk/jsk_apc/pull/1529
```
 (when (member (send (car (last link-list)) :name) (list "right_gripper_vacuum_pad_base" "left_gripper_vacuum_pad_base"))
```
checks `(= name "right_gripper_vacuum_pad_base")` and this will not expected behavior, we need to use `equal` to check them, 
This PR uses
```
(when (member (send (car (last link-list)) :name) (list "right_gripper_vacuum_pad_base" "left_gripper_vacuum_pad_base") :test #'equal)
```
and
Close #1586 

This PR will relax test condition
```
 -    (assert (< (norm (v- av1 av2)) 10))
 +    (assert (< (norm (v- av1 av2)) 90)) ;;
```
The IK changes joint-angle value largely, but it seems only two yaw joint rotates and whole shape arm arm configuration did not change so much, so it is say, in addition to that we added another test
```
+    (send *baxter* :angle-vector av1)
 +    (setq av3 (send-message *baxter* robot-model
 +			    :inverse-kinematics (send (send *baxter* :rarm :end-coords :copy-worldcoords) :translate #f(0 0 -50))
 +			    :move-target (send *baxter* :rarm :end-coords)
 +			    :link-list (send *baxter* :link-list (send *baxter* :right_gripper_vacuum_pad_joint :parent-link) (send *baxter* :rarm :root-link))
 +			    :debug-view t))
 +    (check-result av2 av3)
 +    (assert (and av2 av3))
 +    (assert (< (norm (v- av2 av3)) 5)) ;;
```
which checks Normal IK can solve this test.

https://github.com/start-jsk/jsk_apc/pull/1588/files#diff-db451fb82d2b39cbd79d693e2dd9e8d5R37

**Comment by pazeshun** [comment]
Can you remove tabs?

**Comment by pazeshun** [comment]
I made #1589 to remove tabs that cause travis failing.
Please check #1589

**Comment by k-okada** [comment]
On Mon, May 30, 2016 at 6:43 PM, pazeshun <notifications@github.com> wrote:

> Can you remove tabs?
>
>
sorry, updated PR

--
◉ Kei Okada

**Comment by pazeshun** [comment]
@k-okada Oh, I already update it in #1589
Will I close #1589？

**Comment by pazeshun** [comment]
Closed #1589 
Please merge this

**Comment by k-okada** [comment]
sorry for late

**Pull request merged**
