### PR TITLE
add fc.rosinstall.melodic

### PR DESCRIPTION
**Pull request by knorth55**
add `fc.rosinstall.melodic` for melodic PC

### CODE REVIEW

**Comment by knorth55** [comment]
@pazeshun travis passed. can you review this PR?

**Comment by pazeshun** [comment]
Sorry for late.
I found some packages listed in `.travis.rosinstall.melodic` are not included in this `fc.rosinstall.melodic` (e.g., `rostwitter`, `jsk_demo_common`, `jsk_maps`, `roseus_mongo`, `baxter_moveit_config`, `pr2_gripper_sensor_msgs`, `turtlebot_description`, `kobuki_description`, `create_description`).
Are they released to melodic?
If so, we have to correct `.travis.rosinstall.melodic`, don't we?

**Comment by knorth55** [comment]
- jsk_3rdparty: released (https://github.com/tork-a/jsk_3rdparty-release)
  - rostwitter
- jsk_roseus: released (https://github.com/tork-a/jsk_roseus-release)
  - roseus_mongo
- pr2_gripper_sensor: released (https://github.com/pr2-gbp/pr2_gripper_sensor-release)
  - pr2_gripper_sensor_msgs

- jsk_demos: not released (https://github.com/tork-a/jsk_demos-release)
  - jsk_demo_common
  - jsk_maps
- turtlebot_description: not released
- kobuki_description: not released
- create_description: not release

**Comment by pazeshun** [comment]
Sorry, another question.
Don't we need `octomap_mapping`, `pcl_conversions`, and `perception_pcl` to specify certain versions like `fc.rosinstall.kinetic`?

**Comment by knorth55** [comment]
We do not need to build these because PCL 1.8 is default for melodic 

> Don't we need octomap_mapping, pcl_conversions, and perception_pcl to specify certain versions like fc.rosinstall.kinetic?

**Comment by pazeshun** [comment]
I see, thank you.

**Review by pazeshun — APPROVED** [review]

**Pull request merged**
