### PR TITLE
Use yes_no_button panel in rviz for user input

### PR DESCRIPTION
**Pull request by wkentaro**
image

Please look at lower left.

### CODE REVIEW

**Comment by pazeshun** [comment]
With this PR, do we always have to run Rviz to start picking?

**Comment by wkentaro** [comment]
Use rviz or

```bash
rosrun jsk_rqt_plugins rqt_yn_btn ~:=/rviz/yes_no_button
```

**Comment by pazeshun** [comment]
I understand.
Please also update doc.

**Comment by wkentaro** [comment]
@pazeshun @knorth55 
The demo can be start with `tmuxinator start apc`.
Please avoid to use the baxter user for your daily experiment, but create your account,
because setting up demonstration to check bugs for lab visit takes time.

**Comment by pazeshun** [comment]
@wkentaro Ok, I'll do like that.

**Comment by knorth55** [comment]
@wkentaro 
i dont use tmuxinator, please add doc which rviz you use.

**Comment by knorth55** [comment]
@wkentaro 
sorry, i didnt check this PR properly. thank you for your doc.
when i don't use rviz, creating yes no button is a little bit annoying task for me,  but it's ok.

**Comment by wkentaro** [comment]
https://github.com/start-jsk/jsk_apc/pull/1900 saves the previous behavior (previously the rqt_yn_btn is always launched with main.lanch)
and you can launch yes no button easily with https://github.com/start-jsk/jsk_apc/pull/1899

**Comment by knorth55** [comment]
thx :)

**Pull request merged**
