### PR TITLE
[jsk_2015_05_baxter_apc] Remove approximate_sync (no need)

### PR DESCRIPTION
**Pull request by wkentaro**
This is no need with change in
PR2/pr2_navigation/pr2_navigation_self_filter

Related to https://github.com/PR2/pr2_navigation/pull/24

### CODE REVIEW

**Comment by wkentaro** [comment]
**before**
tiled_23
tiled_32
tiled_63
tiled_72
tiled_81
tiled_111
tiled_120
tiled_129
tiled_160
tiled_169
tiled_200
tiled_209
tiled_218

**Comment by wkentaro** [comment]
*after*
tiled_22
tiled_31
tiled_60
tiled_69
tiled_78
tiled_107
tiled_116
tiled_146
tiled_155
tiled_164

**Comment by wkentaro** [comment]
cc @k-okada 

I think timestamp synchronization is done.
In *before*, sometimes the mask and object position is different, but in *after*, it correctly localized.

**Comment by k-okada** [comment]
great!, how about processing speed? did you get result image in 30hz ? if
not where is the bottleneck?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada 
The bottleneck is robot_self_filter/self_filter

image

**Comment by wkentaro** [comment]
`/extract_indices_right_hand/points_filtered` is the output of `robot_self_filter`.

**Comment by wkentaro** [comment]
fails because of https://github.com/jsk-ros-pkg/jsk_recognition/issues/1363

**Pull request merged**
