### PR TITLE
[Depends on #1662] Add left gripper-v3 to recognition flow

### PR DESCRIPTION
**Pull request by pazeshun**

### CODE REVIEW

**Comment by pazeshun** [comment]
If this is merged before #1662 is merged, robot_self_filter and in_hand_clipper will come not to work.

**Comment by pazeshun** [comment]
Tested in real robot with #1655, #1662, #1663. No more WIP.

**Comment by pazeshun** [comment]
@knorth55 Please review this.

**Comment by knorth55** [comment]
:+1:

**Pull request merged**
