### PR TITLE
[jsk_2016_01_baxter_apc] Run SegmentationInBin algorithm from the beginning to the end

### PR DESCRIPTION
**Pull request by yuyu2172**
'sib' is an acronym for "segmentation in bin".
WIP until I test this launch file on baxter.

### CODE REVIEW

**Comment by yuyu2172** [comment]
Done testing on baxter.
I included bug fixes that are necessary to actually run the algorithm.

Note that timestamp of the output of RBOSegmentationInBinNode has been changed to make subsequent image processing pipelines to work. This is a patch and it should be fixed later when codes are rewritten in C++.

**Comment by yuyu2172** [comment]
sib

**Comment by knorth55** [comment]
+1

**Comment by yuyu2172** [comment]
@wkentaro  please merge if it looks good.

**Pull request merged**
