### PR TITLE
[jsk_2016_01_baxter_apc] Test motion for move-arm-to-bin with rosbag

### PR DESCRIPTION
**Pull request by pazeshun**
From @wkentaro 's suggestion on #1362 
#1362 depends on this to test.

### CODE REVIEW

**Comment by wkentaro** [comment]
+1

**Comment by knorth55** [comment]
@pazeshun can we use this test for master branch?

**Comment by pazeshun** [comment]
@knorth55 
Maybe you can. This test doesn't depend on gripper-v2 branch.

**Comment by knorth55** [comment]
:+1:

**Pull request merged**
