### PR TITLE
[jsk_apc2016_common] Spatial Preprocessing Node

### PR DESCRIPTION
**Pull request by yuyu2172**
related #1439

### CODE REVIEW

**Comment by yuyu2172** [comment]
a new commit in this PR is 'add sib_spatial_preprocessing node'. 
It is not the latest commit in this PR due to rebasing. Don't worry about the order of commits.

**Comment by knorth55** [comment]
`sib_spatial_preprocessing.cpp` should be in package `jsk_2016_01_baxter_apc` according to https://github.com/start-jsk/jsk_apc/pull/1332#issuecomment-214097253

and also you should change its name something like `tf_bbox_to_spatial`.
you don't need to specify `sib` or `preprocessing`.

**Comment by yuyu2172** [comment]
@knorth55 
This should be in package jsk_apc2016_common according to #1332 and #1442.

I agree with the name you proposed.

**Comment by knorth55** [comment]
so you think that tf_bbox_to_mask.py might be in jsk_apc2016_common?
i think ot uses kinect  camera position and it depends on robot.
and in that case, it should be in jsk_2016_01_baxter_apc package

**Comment by yuyu2172** [comment]
Yes, I think that tf_bbox_to_mask should be moved to jsk_apc2016_common.

I disagree your definition of `robot specific code`.
The code, in principle, works on any robots with tf and a camera, such as PR2.
That is the reason why the code should `not`

**Comment by yuyu2172** [comment]
@wkentaro 
ping

**Pull request merged**
