### PR TITLE
Improve ARC2017 pick task program for Mayfes demo

### LINKED ISSUE #2074: Open Lab Demo: Demo on 5/19
# Open Lab Demo
- Date: 2017-05-19 13:00-15:30
- Assignee: @YutoUchimi @708yamaguchi @pazeshun @knorth55

## Videos
https://drive.google.com/open?id=0B5DV6gwLHtyJU19zNy1jRXE2NlE
https://drive.google.com/open?id=0B5DV6gwLHtyJSG9ZWkdiUHRjRGc
https://drive.google.com/open?id=0B5DV6gwLHtyJblExc3UxXzFCbmM

## Launch

```bash
# Launch nodes to control robot.
$ roslaunch jsk_arc2017_baxter baxter.launch

# Launch nodes in recognition pipeline for pick task.
$ roslaunch jsk_arc2017_baxter setup_for_pick.launch

# optional: Check sanity.
# $ rosrun jsk_2016_01_baxter_apc check_sanity_setup_for_pick

# Run task!
$ roslaunch jsk_arc2017_baxter pick.launch json_dir:=$(rospack find jsk_arc2017_common)/data/json/sample_pick_task
```

## Doc
http://jsk-apc.readthedocs.io/en/latest/jsk_arc2017_baxter/arc2017_pick_trial.html

### PR DESCRIPTION
**Pull request by YutoUchimi**
Close #2074

### CODE REVIEW

**Comment by YutoUchimi** [comment]
Usage:
```
$ roslaunch jsk_arc2017_baxter baxter.launch
$ roslaunch jsk_arc2017_baxter setup_for_pick.launch
$ roslaunch jsk_arc2017_baxter pick.launch json_dir:=$(rospack find jsk_arc2017_common)/data/json/easy_pick_task
```
Wait until calibration process finishes, then press "Yes" button on GUI.

**Comment by knorth55** [comment]
This PR includes #2098 #2102 #2105 .
Please merge this after these PR are merged.

**Comment by wkentaro** [comment]
Waiting for https://github.com/start-jsk/jsk_apc/pull/2105

**Comment by knorth55** [comment]
please merge this

**Pull request merged**
