### PR TITLE
[jsk_2016_01_baxter_apc] modify setup_creative.launch to launch devices by serial number

### PR DESCRIPTION
**Pull request by knorth55**
Merge after #1281

### CODE REVIEW

**Comment by pazeshun** [comment]
If you want to use your repository instead of original one, you should update rosinstall file.

**Comment by knorth55** [comment]
@pazeshun thanks, i forgot to send PR

**Comment by knorth55** [comment]
please merge this

**Comment by wkentaro** [comment]
Please rebase.

**Pull request merged**
