### PR TITLE
[jsk_2016_01_baxter_apc] add apc2016 object_data and graspability

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by wkentaro** [comment]
```
- name: item_XXX
  weight: XXX
  graspability:
    - gripper2015: X
    # - vacuum2016:
  stock: X
- name: item_YYY
...
```
is better, no?

**Comment by knorth55** [comment]
that's better

**Comment by wkentaro** [comment]
what's unit of the weight?

**Comment by knorth55** [comment]
unit of every object is oz.
should i modify in to g?

**Comment by wkentaro** [comment]
I see. It's better, but ok at this time.

**Pull request merged**
