### PR TITLE
use c3 for scale

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by k-okada** [comment]
is this temporary setup? or final position of c3 computer?
--
◉ Kei Okada



2019年4月16日(火) 18:07 Shun Hasegawa <notifications@github.com>:

**Comment by knorth55** [comment]
we are introducing one more upboard, and that time I want to make attachment with 3D printer

**Comment by pazeshun** [comment]
Tested with new baxter-c2 and baxter-c3

**Comment by knorth55** [comment]
@pazeshun can you review again?

**Comment by pazeshun** [comment]
Tested with real robot (`roslaunch jsk_arc2017_baxter baxter.launch`, `roslaunch jsk_arc2017_baxter scale.launch`, Commanding movement from `baxter-interface`).

**Comment by pazeshun** [comment]
Current baxter-c2:
DSC_2375
Current baxter-c3:
DSC_2374

**Comment by knorth55** [comment]
@pazeshun can I merge this?

**Comment by pazeshun** [comment]
Yes, please.

**Pull request merged**
