### PR TITLE
[jsk_2015_05_baxter_apc] Generate eus robot model from xacro

### PR DESCRIPTION
**Pull request by wkentaro**
image

### CODE REVIEW

**Comment by pazeshun** [comment]
What this change mean?
This change is permanent?

**Comment by pazeshun** [comment]
Oh, I see.
I think that I will change eus robot model like https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L29-L34 and https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l#L14-L20 for new gripper, so I worried about conflicts.

**Comment by pazeshun** [comment]
Perhaps some files in jsk_2016_01_baxter_apc won't become working because path to xacro files is changed.

**Comment by wkentaro** [comment]
> Perhaps some files in jsk_2016_01_baxter_apc won't become working because path to xacro files is changed.

I fixed it https://github.com/start-jsk/jsk_apc/pull/1250/commits/2079e83811e30d66cd659153d89becaaa7635952 .

**Comment by pazeshun** [comment]
@wkentaro 
Oh, I didn't notice that. Thank you.

**Comment by wkentaro** [comment]
merged via https://github.com/start-jsk/jsk_apc/pull/1251

**Pull request merged**
