### PR TITLE
 add noetic travis test

### PR DESCRIPTION
**Pull request by knorth55**
fix  noetic test
- [x] rosdistro keys
  - https://github.com/ros/rosdistro/pull/30034
  - https://github.com/ros/rosdistro/pull/30035
  - https://github.com/ros/rosdistro/pull/30036
- [x] roseus, jskeus release
- [x] `python3-serial` in `dynamixel_driver
  - https://github.com/pazeshun/dynamixel_motor/pull/5

fix python3 compile test
- [x] fix syntax
- [x] move rbo submodule and fix syntax
~- [ ] https://github.com/yuyu2172/rbo-apc-object-segmentation/pull/3~

```
 + rosdep install -y --rosdistro noetic -n -q --ignore-src --skip-keys=jsk_smart_gui --skip-keys=ros3djs --skip-keys=pr2_calibration_launch --skip-keys=jsk_android_gui_api9 --skip-keys=ros2djs --skip-keys=face_recognition --skip-keys=roslibjs --skip-keys=force_proximity_ros --skip-keys=safe_teleop_base --skip-keys=pcl --from-paths /opt/ros/noetic/share .
  ERROR: the following packages/stacks could not have their rosdep keys resolved
  to system dependencies:
  dualarm_grasping: Cannot locate rosdep definition for [roseus_smach]
  jsk_arc2017_baxter: Cannot locate rosdep definition for [roseus]
  jsk_baxter_startup: Cannot locate rosdep definition for [roseus]
  baxtereus: Cannot locate rosdep definition for [pr2eus]
  jsk_2016_01_baxter_apc: Cannot locate rosdep definition for [roseus]
  jsk_demo_common: Cannot locate rosdep definition for [pr2_gripper_sensor_msgs]
  jsk_maps: Cannot locate rosdep definition for [jskeus]
  jsk_arc2017_common: Cannot locate rosdep definition for [roseus]
  dynamixel_driver: No definition of [python-serial] for OS version [focal]
  jsk_2015_05_baxter_apc: Cannot locate rosdep definition for [roseus]
```

### CODE REVIEW

**Comment by knorth55** [comment]
```
  jsk_2016_01_baxter_apc: Cannot locate rosdep definition for [euscollada]
  jsk_baxter_startup: Cannot locate rosdep definition for [openni_launch]
  baxtereus: Cannot locate rosdep definition for [pr2eus]
  jsk_2015_05_baxter_apc: Cannot locate rosdep definition for [euscollada]
  dynamixel_driver: No definition of [python-serial] for OS version [focal]
  jsk_demo_common: Cannot locate rosdep definition for [pr2_gripper_sensor_msgs]
```

**Comment by knorth55** [comment]
Travis failed because of these missing dependencies. Still long way to release on noetic.

```
  jsk_demo_common: Cannot locate rosdep definition for [pr2_navigation_self_filter]
  pr2eus_tutorials: Cannot locate rosdep definition for [jsk_pr2_startup]
  pr2eus_moveit: Cannot locate rosdep definition for [pr2_moveit_plugins]
  pr2eus: Cannot locate rosdep definition for [pr2_navigation_config]
```

BTW, `pr2eus_tutorials` depends on `jsk_pr2_startup`, which might be a difficult point to release `pr2eus_tutorials`.
https://github.com/jsk-ros-pkg/jsk_pr2eus/commit/f906a52a9836c1384cdda4cfc7d3f5db325335c5

**Comment by pazeshun** [comment]
This PR is included in #2761, right?
I'll merge this PR via #2767.

**Comment by pazeshun** [comment]
Merged via #2767

**Pull request closed without merging**
