### PR TITLE
Abort picking objects when IK to it fails

### PR DESCRIPTION
**Pull request by pazeshun**

### CODE REVIEW

**Comment by pazeshun** [comment]
Tested in real robot

**Comment by pazeshun** [comment]
Sorry for big diff, but most of that is changing indentation.

**Comment by pazeshun** [comment]
I think `:try-to-pick-object` is too big, but I'll make another PR to solve that problem.

**Comment by pazeshun** [comment]
Fixed

**Comment by ban-masa** [comment]
+1

**Pull request merged**
