### PR TITLE
Move astra_hand.launch from setup_for_pick.launch to baxter.launch

### PR DESCRIPTION
**Pull request by YutoUchimi**

### CODE REVIEW

**Comment by knorth55** [comment]
Is this a bug?

**Comment by wkentaro** [comment]
Yeah.

**Comment by wkentaro** [comment]
Missing change in https://github.com/start-jsk/jsk_apc/pull/2085

**Comment by knorth55** [comment]
Why do you move astra launch to baxter launch?

**Comment by wkentaro** [comment]
Because I think it is useful for people who do not use `setup_for_pick.launch`.

**Comment by knorth55** [comment]
camera launch should be included in robot launch, thats true.
jsk_2016 should be, too.

**Pull request merged**
