### PR TITLE
[WIP] [jsk_2016_01_baxter_apc] generate 2016apc world file automatically 

### PR DESCRIPTION
**Pull request by knorth55**
- [ ] fix position in bins

consider about each item's size, otherwise it happens collisions.

- pick_apc.world
screenshot from 2016-02-18 22 08 23
- stow_apc.world
screenshot from 2016-02-18 22 07 21

### CODE REVIEW

**Comment by wkentaro** [comment]
Please rebase origin/master.

**Comment by wkentaro** [comment]
What status is this? untargeted/pending? or wip?

**Comment by knorth55** [comment]
wip

**Comment by wkentaro** [comment]
Maybe this is not necessary for us. Closing at this time.

**Pull request closed without merging**
