### PR TITLE
[jsk_2016_01_baxter_apc] Approach objects straight down

### LINKED ISSUE #1447: [jsk_2016_01_baxter_apc] 小さめの物品を取りにくい
#1432 以前はグリッパーと物品が近づくと、吸引によって小さい物品は引きつけられ、把持することができていた。
#1432 以降は、小さい物品を取ろうとしても、グリッパーの動かし方がよくないと、グリッパーのローカル座標系におけるz軸方向に物品とグリッパーを押し付けることができず、xy平面に平行に物品を押し出してしまうケースがある。

### PR DESCRIPTION
**Pull request by pazeshun**
Fixes #1447 
Details are on #1447

### CODE REVIEW

**Comment by pazeshun** [comment]
Our milestone is done in this PR.

**Comment by wkentaro** [comment]
> Our milestone is done in this PR.

Awesome 👏

**Comment by ban-masa** [comment]
+1

**Comment by knorth55** [comment]
👏👏👏

**Comment by wkentaro** [comment]
@ban-masa @pazeshun Please check slack https://jsk-robotics.slack.com/messages/jsk_apc/ and #1452 .

**Pull request merged**
