### PR TITLE
Stop using VOCdevkit tar file to test extractall function

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/start-jsk/jsk_apc/pull/2702

### CODE REVIEW

**Comment by knorth55** [comment]
LGTM
BTW, are you using VOC data in occlsegm or grasp fusion?
if so, we should  switch to google drive link to download it.

**Comment by wkentaro** [comment]
This is devkit, not dataset, so should be fine, right?

**Comment by wkentaro** [comment]
I found that 5MB.zip is not actually the zip file.

**Comment by knorth55** [comment]
LGTM. I prefer using `hub` released tar.gz.

**Pull request merged**
