### PR TITLE
[WIP] [jsk_2016_01_baxter_apc] add test code for jsk_2016_01_baxter_apc

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
from https://github.com/start-jsk/jsk_apc/pull/1030#issuecomment-177945997

apc 2016のbaxter_pick.launchを行うとこのようなエラーが出てenable_robot.pyもできませんでした。
```
[ERROR] [WallTime: 1454328921.570767] [0.000000] RobotEnable: Software Version Mismatch.
Robot Software version (1.1.0) does not match local SDK version (1.2.0). Please
Update your Robot Software. See: http://sdk.rethinkrobotics.com/wiki/Software_Update
```

**Comment by k-okada** [comment]
solution was found by https://github.com/start-jsk/jsk_apc/pull/1030#issuecomment-177978272

**Comment by wkentaro** [comment]
What status is this PR?

**Comment by wkentaro** [comment]
Closing now.

**Pull request closed without merging**
