### PR TITLE
Change vacuum pad to short one(SPB2f)

### PR DESCRIPTION
**Pull request by pazeshun**
From #1696

### CODE REVIEW

**Comment by pazeshun** [comment]
New collision link:
screenshot from 2016-06-14 14 01 03
screenshot from 2016-06-14 14 01 42
end-coords of eus model:
screenshot from 2016-06-14 14 14 39

**Comment by ban-masa** [comment]
+1

**Comment by pazeshun** [comment]
Tested in real robot

**Comment by pazeshun** [comment]
@knorth55 Please test this in stow task. If you have any opinions, please tell me through #1696

**Comment by knorth55** [comment]
ok

**Pull request merged**
