### PR TITLE
add scale key in move-arm-body->bin

### LINKED ISSUE #1689: Move too quickly in :move-arm-body->bin
Arms move too quickly so that some heavy objects fall down.
- [x] quick start action

### PR DESCRIPTION
**Pull request by knorth55**
Partly fix #1689

### CODE REVIEW

**Comment by pazeshun** [comment]
Please test this in real robot.

**Comment by knorth55** [comment]
fixed

**Comment by knorth55** [comment]
already tested, but i made a mistake to make a commit

**Comment by pazeshun** [comment]
+1

**Pull request merged**
