### PR TITLE
[2016apc] add visualize program for recognition and modify pick_kiva.world.erb to create world file with JSON

### PR DESCRIPTION
**Pull request by knorth55**
- visualization program for recognition 
[2016apc] add visualize program for recognition
- JSON file -> world file  
[2016apc] add JSON parser and create world file from JSON file

### CODE REVIEW

**Comment by knorth55** [comment]
screenshot from 2016-02-04 05 10 54
screenshot from 2016-02-04 06 55 31
Upper : recognition program
Lower : load world file created from JSON

**Comment by k-okada** [comment]
nice @wkentaro please review

**Comment by wkentaro** [comment]
Looks good tentatively, you can write more generalized visualization program when you have time.
But I think you should split this to two PRs:

1. Visualization program for object recognition in bin
1. Generate world file from JSON file

**Comment by knorth55** [comment]
PR devided in #1044  and #1045

**Comment by knorth55** [comment]
thank you @wkentaro

**Pull request closed without merging**
