### PR TITLE
use travis not jenkins

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by k-okada** [comment]
@k-okada and @wkentaro is working on travis/jenkins issue, so you can focus on robot motion / recognition improvement,

**Comment by knorth55** [comment]
i make this PR with @wkentaro.

**Comment by k-okada** [comment]
ok, @wkentaro can you speed up or reduce dates in  `download_test_data`
```
[jsk_2016_01_baxter_apc:make] cd /home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/travis/ros/ws_jsk_apc/src/jsk_apc/jsk_2016_01_baxter_apc /home/travis/ros/ws_jsk_apc/src/jsk_apc/jsk_2016_01_baxter_apc /home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc /home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc /home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/download_test_data.dir/DependInfo.cmake --color=
[jsk_2016_01_baxter_apc:make] Dependee "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/clean_test_results_jsk_2016_01_baxter_apc.dir/DependInfo.cmake" is newer than depender "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/clean_test_results_jsk_2016_01_baxter_apc.dir/depend.internal".
[jsk_2016_01_baxter_apc:make] Dependee "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/clean_test_results_jsk_2016_01_baxter_apc.dir/depend.internal".
[jsk_2016_01_baxter_apc:make] Dependee "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/download_test_data.dir/DependInfo.cmake" is newer than depender "/home/travis/ros/ws_jsk_apc/build/jsk_2016_01_baxter_apc/CMakeFiles/download_test_data.dir/depend.internal".
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by knorth55** [comment]
thank you :)

**Comment by wkentaro** [comment]
> ok, @wkentaro can you speed up or reduce dates in download_test_data

It is difficult to make it faster, it supports both caching and decompressing.
Maybe I did as far as I can.

**Comment by k-okada** [comment]
it seems something wrong on downloading, if I C-c and run `catkin run_tests` again, then it works, so someting happens only the first time
```
k-okada   4686  3.0  0.2 460044 25972 pts/0    Sl+  15:32   0:31 /usr/bin/python /usr/local/bin/catkin run_tests jsk_2016_01_baxter_apc --start-with-this --force-cmake
k-okada   4965  0.0  0.0  12900  3024 pts/0    S+   15:32   0:00 /usr/bin/make run_tests --jobserver-fds=6,7 -j
k-okada   4973  0.0  0.0  13304  3340 pts/0    S+   15:32   0:00 /usr/bin/make -f CMakeFiles/Makefile2 run_tests
k-okada   4982  0.0  0.0  13304  3460 pts/0    S+   15:32   0:00 /usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/run_tests.dir/all
k-okada   4990  0.0  0.0  12512  2644 pts/0    S+   15:32   0:00 /usr/bin/make -f CMakeFiles/download_test_data.dir/build.make CMakeFiles/download_test_data.dir/build
k-okada   4992  0.0  0.1  79172 20936 pts/0    S+   15:32   0:00 python /home/k-okada/catkin_ws/ws_jsk_apc/src/jsk_apc/jsk_2016_01_baxter_apc/scripts/download_test_data.py
root      5740  0.0  0.0      0     0 ?        S    15:32   0:00 [kworker/1:0]
k-okada   7557  0.0  0.0  35036 10884 pts/0    S+   15:34   0:00 /usr/bin/python /usr/local/bin/gdown https://drive.google.com/uc?id=0BzBTxmVQJTrGRERod3E5S3RxdE0 -O /home/k-okada/.ros/data/sib_kinect2.bag.tar.gz --quiet
k-okada   7584  0.0  0.0   4452   772 pts/0    S+   15:34   0:00 /bin/sh -c wget --load-cookie /tmp/cookie.txt --quiet --save-cookie /tmp/cookie.txt "https://docs.google.com/uc?export=download&confirm=CzV4&id=0BzBTxmVQJTrGRERod3E5S3RxdE0" -O /home/k-okada/.ros/data/sib_kinect2.bag.tar.gz
k-okada   7585  0.4  0.0  38392  5548 pts/0    S+   15:34   0:04 wget --load-cookie /tmp/cookie.txt --quiet --save-cookie /tmp/cookie.txt https://docs.google.com/uc?export=download&confirm=CzV4&id=0BzBTxmVQJTrGRERod3E5S3RxdE0 -O /home/k-okada/.ros/data/sib_kinect2.bag.tar.gz
```
it seeems

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/1618

**Pull request closed without merging**
