### PR TITLE
add moveit config for grippper-v6

### PR DESCRIPTION
**Pull request by knorth55**
Merge after #2155 
I haven't tested with real robot yet.

### CODE REVIEW

**Comment by knorth55** [comment]
I tested with real robot and euslisp.

Videos:
https://drive.google.com/open?id=0B5DV6gwLHtyJck5zdkk0SWFkV0U
https://drive.google.com/open?id=0B5DV6gwLHtyJeWJpU09WVUJJUU0

**Comment by pazeshun** [comment]
Please rebase #2155

**Comment by pazeshun** [comment]
Works for real task with #2155! Thanks!

**Comment by wkentaro** [comment]
I merged https://github.com/start-jsk/jsk_apc/pull/2155, please resolve the conflicts.

**Comment by knorth55** [comment]
Rebased

**Comment by knorth55** [comment]
@pazeshun could you please review this?

**Pull request merged**
