### PR TITLE
Adjust right gripper firmware to gripper-v4

### PR DESCRIPTION
**Pull request by pazeshun**
#1856

### CODE REVIEW

**Comment by pazeshun** [comment]
This firmware was already written to arduino

**Comment by k-okada** [comment]
これは機構が変わったの？

**Comment by k-okada** [comment]
did you changed the gripper mechanism?or this is just a bug

**Comment by pazeshun** [comment]
The gripper mechanism was changed. The pose of servo motor was inverted.

**Comment by pazeshun** [comment]
Now poses of right gripper servo and left gripper servo are symmetrical.

**Pull request merged**
