### PR TITLE
interface_generator for json file

### PR DESCRIPTION
**Pull request by kimhc6028**

### CODE REVIEW

**Comment by wkentaro** [comment]
Could you please clean the commit logs?

**Comment by knorth55** [comment]
can you tell me directory where the json files are generated by this program?

**Comment by kimhc6028** [comment]
@wkentaro I understood
@knorth55 json files are now  generated to scripts directory. Where should I generate generate files?

**Comment by knorth55** [comment]
json files should be generated in /json dir

**Pull request closed without merging**
