### PR TITLE
[jsk_apc2016_common] Publish_bin_info now publishes tf frame of bin

### PR DESCRIPTION
**Pull request by yuyu2172**
I did two things in this PR.
Bin's frame did not exist previously. This PR publishes those frames by using BoundingBoxes. The published frame simplifies pre-processing spatial features. Rewrite of the pre-processing is under way. 
 
Also, BinInfo msg now includes header which is beneficial in two ways.
1. frame_id: used to locate frame of the bin
2. stamp: used by message filter.

### CODE REVIEW

**Comment by knorth55** [comment]
can you split tf publish function into one another node? I don't see any necessity of having this function in this node.

**Comment by yuyu2172** [comment]
that works with me

**Comment by knorth55** [comment]
what do you mean?

**Comment by knorth55** [comment]
ah, i got it

**Comment by yuyu2172** [comment]
I guess "that works *for* me" should be the correct phrase. I learned something. Thanks.

**Comment by yuyu2172** [comment]
@knorth55 
ping

**Comment by knorth55** [comment]
+1
can you put a screenshot of tf_echo or view_frames?

**Comment by yuyu2172** [comment]
sure

**Pull request merged**
