### PR TITLE
[jsk_2016_01_baxter_apc] add right arm depthsense camera

### PR DESCRIPTION
**Pull request by knorth55**
Merge after #1285

### CODE REVIEW

**Comment by knorth55** [comment]
Please merge this

**Comment by wkentaro** [comment]
Travis test fails.
```
DOCKER_CONTAINER_NAME   = start-jsk.jsk_apc_123091886

Traceback (most recent call last):
  File "./.travis/travis_jenkins.py", line 305, in 
    j.reconfig_job(job_name, CONFIGURE_XML % locals())
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 882, in reconfig_job
    DEFAULT_HEADERS))
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 361, in jenkins_open
    e.code, e.msg)
jenkins.JenkinsException: Error in request. Possibly authentication failed [500]: Server Error
+++exit 1
++++'[' 3 = 1 ']'
```
it seems jenkins has error.

**Comment by knorth55** [comment]
what does mean? jenkins died?

**Comment by wkentaro** [comment]
probably.

--
和田 健太郎 / Kentaro Wada
http://wkentaro.com/

2016年4月15日 3:32 +0900 に Shingo Kitagawa<notifications@github.com>は書きました:

**Comment by wkentaro** [comment]
I fixed it https://github.com/start-jsk/jsk_apc/pull/1294

**Comment by knorth55** [comment]
thank you :)

**Pull request merged**
