### PR TITLE
[WIP] Compute IK from some predeined poses

### LINKED ISSUE #1459: [jsk_2016_01_baxter_apc] Too verbose testing in test_move_arm_to_bin
## Solution

- Stop using inverse-kinematics in baxter-util.l.

## Status

```
$ rostest jsk_2016_01_baxter_apc test_move_arm_to_bin.test --text

....
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for slow ik, try to start from good position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, staring from relaxed position



                                                                                
[jsk_2016_01_baxter_apc:make] ; failed for normal ik, try to move arms vely slowly


```

### PR DESCRIPTION
**Pull request by wkentaro**
I just copied method from jsk_2015_05_baxter_apc.

- :angle-vector (current-position)
- :reset-pose
- :reset-manip-pose
- :fold-pose-upper
- :fold-pose-middle
- :fold-pose-lower
- :fold-pose-back

This also fixes #1459

### CODE REVIEW

**Comment by pazeshun** [comment]
I don't understand why this PR solves #1459 
At last you use inverse-kinematics in baxter-util.l, don't you?

**Comment by pazeshun** [comment]
Also, I have a question: Will you stop using slow IK?
I think this PR decrease IK solvable resion

**Comment by wkentaro** [comment]
> I don't understand why this PR solves #1459 

because this PR overwrites `:inverse-kinematics` in baxter-util.l. So this suppress the print output.

> At last you use inverse-kinematics in baxter-util.l, don't you?

In jsk_2015_05_baxter_apc, no.

**Comment by wkentaro** [comment]
> Also, I have a question: Will you stop using slow IK?

I can add the features. 
- from rotationl-axis nil: https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-util.l#L8
- slow ik: https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-util.l#L18


> I think this PR decrease IK solvable region

I'm not sure how efficient the slow ik, but in baxter-util.l there is only two prepared poses, so from my experience this does not work well (current pose, untuck-pose).
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-util.l#L18

>

**Comment by pazeshun** [comment]
inverse-kinematics you wrote in this PR is in jsk_2015_baxter_apc::baxter-robot and its super class is baxter-robot defined in baxter-util, isn't it?
So I think send-super* inverse-kinematics calls inverse-kinematics in baxter-util

**Comment by wkentaro** [comment]
> inverse-kinematics you wrote in this PR is in jsk_2016_01_baxter_apc::baxter-robot and its super class is baxter-robot defined in baxter-util, isn't it?
So I think send-super* :inverse-kinematics calls inverse-kinematics in baxter-util

That was what I overlooked. But maybe this cannot be fixed.
I will change the IK behavior in baxtereus/baxter-util.l

**Comment by pazeshun** [comment]
> I will change the IK behavior in baxtereus/baxter-util.l

I sometimes want to know if normal IK fails and revert if normal IK fails.
So I also want to change IK behavior in baxtereus/baxter-util.l for us to be able to select on/off of IK staring from relaxed position and slow IK.
I think this is also solution for the problem of this PR.

**Comment by wkentaro** [comment]
> I think this is also solution for the problem of this PR.

This PR is to enhance :inverse-kinematics to be independent the current pose.
And your need is selecting simple/complex inverse kinematics computation (I mean strategic ik in baxter-util with *complex*).
It seems different.

**Comment by pazeshun** [comment]
Sorry for lack of words in my previous comment.
I want to say:
1. Fix IK behavior in baxtereus/baxter-util.l for us to be able to select simple/complex inverse kinematics computation.
2. Select simple inverse kinematics computation in baxtereus/baxter-util.l, and usually add complex inverse kinematics computation in this PR.
3. Also, we can on/off complex inverse kinematics computation.
If you think it is too complex system, then don't care about my comment.

**Comment by k-okada** [comment]
I think you can update baxtereus/baxter-utill.l

**Comment by wkentaro** [comment]
Yeah, already sent pr https://github.com/jsk-ros-pkg/jsk_robot/pull/602

**Comment by k-okada** [comment]
i just found that , sorry.

**Comment by pazeshun** [comment]
Ok, so don't care about my comments.
I'll send PR to jsk-ros-pkg/jsk_robot when I need.

**Comment by pazeshun** [comment]
This PR is waiting for release of jsk_robot 1.0.6, right?

**Comment by pazeshun** [comment]
Please change `:inverse-kinemtatics` when you want to merge this because `baxter.l` in master branch already has `:inverse-kinematics`

**Comment by wkentaro** [comment]
You said currently the ik did not fail and this was not necessary. This PR is waiting for when it becomes required.

**Comment by pazeshun** [comment]
Oh, thank you for reminding me.

**Comment by wkentaro** [comment]
Maybe this is done in https://github.com/start-jsk/jsk_apc/pull/1798

**Pull request closed without merging**
