### PR TITLE
[jsk_apc2016_common] rbo_segmentation_in_bin_node returns nothing when it fails to predict anything

### PR DESCRIPTION
**Pull request by yuyu2172**
#1519 

@knorth55, @pazeshun 
We need to change `main.l` to handle cases when rbo_sib fails.

### CODE REVIEW

**Comment by pazeshun** [comment]
I think we should change main.l based on #1518

**Comment by knorth55** [comment]
now, if it returns nothing, `main.l` do not try to pick. 
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L334-L338

**Comment by pazeshun** [comment]
In that case, we should use old segmentation system in stead of giving up, I think.

**Comment by knorth55** [comment]
i think it depends on how SIB node's msg looks like.

when it cannot get result and it doesnot send a msg, there is no problem.
However, it cannot get result but send a msg like NaN, it cause a problem.
we can stop this error in SIB node.

**Comment by yuyu2172** [comment]
`:recognize-objects-segmentation-in-bin` in `baxter-interface.l` keeps running in while loop when SIB returns nothing.
This method should timeout when nothing is returned and proceed.

**Comment by yuyu2172** [comment]
@knorth55 
ping

**Comment by knorth55** [comment]
pong

**Pull request merged**
