### PR TITLE
[jsk_2016_01_baxter_apc] fix bug in main.l and add euslint test

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by wkentaro** [comment]
Please try https://github.com/start-jsk/jsk_apc/tree/euslint
and add test with `jsk_tools_add_shell_test` in CMakeLists.txt.

**Comment by knorth55** [comment]
like this?
i tried euslint with error code and it doesn't pass error result to catkin.

**Comment by wkentaro** [comment]
lgtm

**Comment by knorth55** [comment]
it seems catkin does not trap euslint error, doesn't it?
I tried without fix-bug commit , andit passed run_test in my env.

**Comment by pazeshun** [comment]
Does this bug cause something bad? If it does, I'll cherry-pick this PR to gripper-v2 branch immediately.
If it doesn't, I think I don't have to hurry.

**Comment by wkentaro** [comment]
> Does this bug cause something bad? If it does, I'll cherry-pick this PR to gripper-v2 branch immediately.
If it doesn't, I think I don't have to hurry.

@knorth55

**Pull request merged**
