### PR TITLE
Change FA-I-sensor to root repository in *.rosinstall

### PR DESCRIPTION
**Pull request by pazeshun**
Because https://github.com/RoboticMaterials/FA-I-sensor/pull/11 is merged

### CODE REVIEW

**Comment by knorth55** [comment]
travis failed because of setuptools
this PR fixes this problem https://github.com/locusrobotics/catkin_virtualenv/pull/49

**Comment by pazeshun** [comment]
@knorth55 Thank you.
Just FYI:
This setuptools problem seems due to some PyPA mirrors which wrongly drop `python_requires = >=3.5` setting:
https://github.com/pypa/virtualenv/issues/1493#issuecomment-573461695
https://github.com/pypa/pip/issues/7586#issuecomment-573460206

**Comment by knorth55** [comment]
so, we need to wait for a while and the problem will be solved?

**Comment by pazeshun** [comment]
> so, we need to wait for a while and the problem will be solved?

We just have to wait for https://github.com/locusrobotics/catkin_virtualenv/pull/49 to be released.
The wrong mirrors don't seem fixed yet, so https://github.com/locusrobotics/catkin_virtualenv/pull/49 explicitly install `setuptools<45` to stop downloading setuptools 45.0.0.

**Comment by pazeshun** [comment]
@knorth55 
BTW, will chainer problem on Python 2 be fixed?
I think https://github.com/chainer/chainer/pull/8517 should be included in chainer 7.0.0, otherwise 7.0.0 remains to be installed on Python 2.
However, I couldn't find `python_requires` in https://github.com/chainer/chainer/blob/v7.0.0/setup.py and https://github.com/chainer/chainer/blob/v7.0.0/setup.cfg.

**Comment by knorth55** [comment]
I hoped so, but they released in chainer v7.1.0

**Comment by pazeshun** [comment]
I commented the issue: https://github.com/chainer/chainer/pull/8517#issuecomment-576128957

**Comment by knorth55** [comment]
@pazeshun can I merge this? the chainer problem does not seem to be solved and it is not related to this PR.

**Comment by pazeshun** [comment]
@knorth55 Yes, please merge this.

**Pull request merged**
