### PR TITLE
Revert "[jsk_apc2016_common] publish_bin_tf now uses tf2_ros static_tf_publisher"

### PR DESCRIPTION
**Pull request by wkentaro**
Reverts start-jsk/jsk_apc#1493

### CODE REVIEW

**Comment by wkentaro** [comment]
requested by @yuyu2172

**Comment by k-okada** [comment]
@yuyu2172 what was the problem?

--
◉ Kei Okada

**Comment by yuyu2172** [comment]
There was a bug.
It only instantiates one publisher even though it should instantiate twelve.

**Comment by k-okada** [comment]
how can I reproduce this "bug"

--
◉ Kei Okada

**Pull request merged**
