### PR TITLE
use VOC dataset in google drive

### PR DESCRIPTION
**Pull request by knorth55**
official website seems down ;(
This PR fixes Travis build failure.

### CODE REVIEW

**Comment by knorth55** [comment]
VOC official site is now working but it seems unstable.
should we switch to our own google drive?

**Comment by pazeshun** [comment]
> should we switch to our own google drive?

I feel this is better, because I don't trust official website much.
However, repeating this will make what we manage too much...
@knorth55 What's your opinion? If you don't trust official one, either, let's switch to our google drive.

**Comment by wkentaro** [comment]
This is only for the test, right? Maybe we should use more trustable test files: e.g., https://www.thinkbroadband.com/download

**Comment by wkentaro** [comment]
Sent PR https://github.com/start-jsk/jsk_apc/pull/2703

**Pull request closed without merging**
