### PR TITLE
[WIP] Add gripper-v6 to baxter right hand

### PR DESCRIPTION
**Pull request by pazeshun**
@knorth55 
Can you add moveit to new baxter robot model?

### CODE REVIEW

**Comment by pazeshun** [comment]
Rebase origin/master

**Comment by knorth55** [comment]
> @knorth55
Can you add moveit to new baxter robot model?

you can do stow task and pick task without moveit with `:moveit nil`.
please try it first.

**Comment by pazeshun** [comment]
> you can do stow task and pick task without moveit with :moveit nil.
> please try it first.

Ok, I'll do

**Comment by pazeshun** [comment]
Rebase origin/master

**Comment by pazeshun** [comment]
Rebase #2144 
Depends on #2144

**Comment by pazeshun** [comment]
We need #2124 for using Astra mini s
The new version ( #2155 ) is based on #2124

**Pull request closed without merging**
