### PR TITLE
[Depends on #1662, #1656] Adjust left arm motion to right arm

### PR DESCRIPTION
**Pull request by pazeshun**

### CODE REVIEW

**Comment by pazeshun** [comment]
@ban-masa Please review the last commit. Other commits are in #1662

**Comment by pazeshun** [comment]
Without #1656 , recognition in real robot won't work.

**Comment by ban-masa** [comment]
GJ :+1:

**Comment by pazeshun** [comment]
Tested in real robot with #1655, #1662, #1656. No more WIP.
Please merge this.

**Pull request merged**
