### PR TITLE
Add urdf checking launch

### PR DESCRIPTION
**Pull request by pazeshun**
For checking URDF easily.

### CODE REVIEW

**Comment by knorth55** [comment]
can you paste screenshot?

**Comment by pazeshun** [comment]
You can check URDF with `roslaunch jsk_2016_01_baxter_apc check_baxter_urdf.launch` like below.
screenshot from 2016-11-07 00 01 14
You can also change joint angle easily with GUI.
screenshot from 2016-11-07 00 01 44

**Comment by knorth55** [comment]
:+1:

**Comment by pazeshun** [comment]
@wkentaro Please merge this

**Pull request merged**
