### PR TITLE
[jsk_apc2016_common] object_data_2016 yaml style fixed

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by wkentaro** [comment]
Please update the test.

**Comment by wkentaro** [comment]
And include this kind of PR to #1536 next time.

**Comment by wkentaro** [comment]
This is already included in #1536. duplicated

**Comment by knorth55** [comment]
i think it is better to check separately, so i separated into two PR

**Comment by knorth55** [comment]
#1536 and this PR solve different issue, it should be different PR

**Comment by wkentaro** [comment]
> #1536 and this PR solve different issue, it should be different PR

I don't think they are solving same issue. I'm not sure why it should be separated..
"Use graspability after https://github.com/start-jsk/jsk_apc/issues/1354"

**Comment by wkentaro** [comment]
> Please update the test.

**Comment by knorth55** [comment]
> I don't think they are solving same issue. I'm not sure why it should be separated..


there are two issues
- modify work_order to apply for apc2016 #1536
- object_data yaml style is not proper this PR

**Comment by knorth55** [comment]
> "Use graspability after #1354"

is this a comment for #1536 ?

**Comment by knorth55** [comment]
i will ipdate the test

**Comment by knorth55** [comment]
updated

**Comment by pazeshun** [comment]
I want to define graspability for new gripper based on this PR, so I prefer separating.

**Comment by knorth55** [comment]
@wkentaro ping

**Pull request merged**
