### PR TITLE
[jsk_apc2016_common] fixed rosparam target_bin

### PR DESCRIPTION
**Pull request by yuyu2172**

### CODE REVIEW

**Comment by knorth55** [comment]
why did you change param name?
in `main.l`, param name is `target_bin`.
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/main.l#L59

**Comment by yuyu2172** [comment]
`target_bin` is ambiguous, and inconsistent with publish_target_bin_info.py.

**Comment by knorth55** [comment]
sure

**Comment by yuyu2172** [comment]
maybe in the future

**Pull request closed without merging**
