### PR TITLE
Add left gripper_v7 model

### PR DESCRIPTION
**Pull request by pazeshun**
## What is added
* Mesh model of new gripper (left gripper_v7)
* URDF of Baxter with left gripper_v7 (baxterlgv7)
  * Header files and source file to describe tendon transmission (used by gripper controller)

screenshot from 2017-12-09 17 15 59
* Auto generation of Euslisp model of baxterlgv7
screenshot from 2017-12-09 17 29 44
  * Slightly lighter than current baxter model
     ```
     $ du -k baxter.l baxterlgv7.l 
     34508	baxter.l
     34380	baxterlgv7.l
     ```

### CODE REVIEW

**Comment by pazeshun** [comment]
@knorth55 Can you review this?

**Comment by knorth55** [comment]
This PR is huge.
Can you tell me what I should check?

**Comment by pazeshun** [comment]
Main purpose of this PR is to add mesh files (STL), xacro files and an Euslisp model file.
It is not so difficult, and you can nearly skip.
But `left_gripper_v7.xacro` depends on tendon transmission, which is described by a cpp file, header files, and `ros_control_plugins.xml`
This makes PR complicated, and you cannot understand without knowledge about ros_control.
I've found that I can add tests of tendon transmission, so I'll add so that you can totally skip this PR.
Back to WIP.

**Comment by pazeshun** [comment]
> This PR is huge.

Then, I have to split this PR to 3 parts:
- Add tendon transmission and tests of it
- Add URDF
- Add Euslisp model

**Comment by pazeshun** [comment]
> I've found that I can add tests of tendon transmission, so I'll add so that you can totally skip this PR.

I'll do this in another PR.
@knorth55 can you approve this?

**Comment by pazeshun** [comment]
Merge origin/master

**Comment by pazeshun** [comment]
Test passed!
@knorth55 Can you merge this?

**Pull request merged**
