### PR TITLE
[jsk_apc2016_common][Depends on #1443] make RBO segmentation without preprocessing

### PR DESCRIPTION
**Pull request by yuyu2172**
I made a node that does RBO SIB with very little layer on top of it. Unlike the existing rbo_segmentation_in_bin_node.py, it does not do preprocessing by itself.

For the time being, I put this in a directory "jsk_apc2016_common/node_scripts", and left the existing one. I will delete old codes once transition completes.

### CODE REVIEW

**Comment by yuyu2172** [comment]
Sample output
screenshot from 2016-05-12 20 07 32

launch file I used
```
<launch>
  <!-- shelf-->
  <arg name="json" default="$(find jsk_2015_05_baxter_apc)/json/layout_12.json"/>
  <arg name="UPPER_SHELF" value="$(find jsk_apc2016_common)/config/bin_upper_shelf.yaml"/>
  <arg name="LOWER_SHELF" value="$(find jsk_apc2016_common)/config/bin_lower_shelf.yaml"/>

  <!-- camera-->
  <arg name="INPUT_POINTS" value="/kinect2_torso/hd/points"/>
  <arg name="INPUT_INFO" value="/kinect2_torso/hd/camera_info"/>
  <arg name="INPUT_IMAGE" value="/kinect2_torso/hd/image_color"/>

  <!-- target bin-->
  <arg name="INPUT_BIN_ARRAY" value="/set_bin_param/bin_array"/>
  <arg name="INPUT_TARGET" value="/right_hand/target_bin"/>
  <arg name="TARGET_BIN" value="g"/>
  <arg name="TRAINED_PATH" value="$(find jsk_apc2016_common)/data/trained_segmenter.pkl" />

  <param name="/right_hand/target_bin" value="$(arg TARGET_BIN)"/>

  <node pkg="jsk_apc2016_common" type="publish_bin_info.py"
    name="set_bin_param">
    <param name="json" value="$(arg json)"/>
    <rosparam file="$(arg UPPER_SHELF)" command="load" ns="upper_shelf"/>
    <rosparam file="$(arg LOWER_SHELF)" command="load" ns="lower_shelf"/>
  </node>

  <node pkg="jsk_apc2016_common" type="publish_target_bin_info.py"
    name="pub_target_bin_info" output="screen">
    <remap from="~target_bin_name" to="$(arg INPUT_TARGET)"/>
    <remap from="~input/bin_info_array" to="$(arg INPUT_BIN_ARRAY)"/>
  </node>

  <node pkg="jsk_apc2016_common" type="publish_bin_tf.py"
    name="pub_bin_tf">
    <remap from="~input/bin_info_array" to="$(arg INPUT_BIN_ARRAY)"/>
  </node>

  <node pkg="jsk_apc2016_common" type="sib_spatial_preprocessing"
    name="sib_spatial" output="screen">
    <remap from="~input" to="$(arg INPUT_POINTS)"/>
    <remap from="~target_bin" to="/pub_target_bin_info/target_bin_info"/>
  </node>

  <node pkg="jsk_2016_01_baxter_apc" type="tf_bbox_to_mask.py"
      name="sib_mask" output="screen">
    <remap from="~input/bin_info_array" to="$(arg INPUT_BIN_ARRAY)"/>
    <remap from="~target_bin_name" to="$(arg INPUT_TARGET)"/>
    <remap from="~input" to="$(arg INPUT_INFO)"/>
  </node>

  <node pkg="jsk_apc2016_common" type="rbo_segmentation_in_bin_node.py"
        name="sib_rbo" output="screen">
    <remap from="~input/dist" to="/sib_spatial/dist"/>
    <remap from="~input/height" to="/sib_spatial/height"/>
    <remap from="~input/image" to="$(arg INPUT_IMAGE)"/>
    <remap from="~input/mask" to="/sib_mask/output"/>
    <remap from="~input/bin_info_array" to="$(arg INPUT_BIN_ARRAY)"/>
    <remap from="~target_bin_name" to="$(arg INPUT_TARGET)"/>
    <param name="trained_pkl_path" value="$(arg TRAINED_PATH)" />
  </node>
</launch>
```

**Comment by yuyu2172** [comment]
new commits in this PR are 'segmentation_in_bin node' and 'fixed some parameter and mistakes'.

**Comment by knorth55** [comment]
can you squash 'fixed some parameter and mistakes'?

**Comment by yuyu2172** [comment]
@knorth55 
I think otherwise about the guideline.
The two commits are dealing with two different issues. The second one fixed bugs introduced in the previous PRs and the first one introduces a new feature Since we accept bug fixes as PR, I thought it was fine.
What do you think?

**Comment by knorth55** [comment]
i dont like 'fix mistakes' because it does not tell anything
you should specify more
and parameter modification is different from mistakes, and it should be split to another commit

**Comment by yuyu2172** [comment]
@wkentaro 
travis does not start. Do you know why?

**Pull request merged**
