### PR TITLE
Avoid collision to bin top in return_object and try-to-pick-object

### LINKED ISSUE #1669: Gripper hit Bin top in return_object and try-to-pick-object
I overlooked this in #1638

### PR DESCRIPTION
**Pull request by pazeshun**
Fixes #1669

### CODE REVIEW

**Comment by pazeshun** [comment]
@ban-masa Please review 1d47063 5f4510e .
Other commits are in #1663

**Comment by pazeshun** [comment]
rebase origin/master

**Comment by pazeshun** [comment]
@ban-masa @wkentaro  Please review and merge this PR as soon as possible because the robot may do danger movement without this.

**Comment by ban-masa** [comment]
OK. I'll do my best.

**Comment by ban-masa** [comment]
+1

**Comment by pazeshun** [comment]
@ban-masa Thank you for your fast reply!

**Pull request merged**
