### PR TITLE
[WIP] Add jsk_pr2eus package to fc.rosinstall

### PR DESCRIPTION
**Pull request by pazeshun**
To fix https://github.com/jsk-ros-pkg/jsk_robot/issues/738

### CODE REVIEW

**Comment by pazeshun** [comment]
I need this regardless of how to fix because I have to change the behavior of `:angle-vector-sequence` anyway.

**Comment by knorth55** [comment]
@pazeshun this branch is master, and you are waiting for release? I think we do not need to update this fc.rosinstall for waiting for release

**Comment by pazeshun** [comment]
Sorry, perhaps this is not needed.

**Comment by pazeshun** [comment]
We don't need this because the problem will be fixed in https://github.com/wkentaro/baxter_interface/pull/1

**Pull request closed without merging**
