### PR TITLE
[jsk_2016_01_baxter_apc] detect :inverse-kinematics nil return

### PR DESCRIPTION
**Pull request by knorth55**
critical error occurs. main.l process has died.

### CODE REVIEW

**Comment by pazeshun** [comment]
+1
Please tell me about the condition in which IK failed like #1470

**Comment by knorth55** [comment]
bin k

**Comment by pazeshun** [comment]
I want to know where is target coordinate
We have to do experiment to know that

**Comment by knorth55** [comment]
condition is same as #1650

**Pull request merged**
