### PR TITLE
add table removal program for sample_fetch_object_segmentation

### PR DESCRIPTION
**Pull request by 708yamaguchi**
merge after #2020

### CODE REVIEW

**Comment by k-okada** [comment]
> fetch_openni_local.launch

元々動いているfetch_bringup とコンフリクトしない？

--
◉ Kei Okada


2017-03-07 16:45 GMT+09:00 708yamaguchi <notifications@github.com>:

**Comment by 708yamaguchi** [comment]
コンフリクトはしていないと思います。

**Comment by 708yamaguchi** [comment]
before
fetch_3d_detection_before

after
fetch_3d_detection_after

**Comment by k-okada** [comment]
あ、load driver falseか．了解．

 +    <include file="$(find openni2_launch)/launch/openni2.launch">
 +      <arg name="load_driver" value="false" />

--
◉ Kei Okada


2017-03-07 17:36 GMT+09:00 708yamaguchi <notifications@github.com>:

**Pull request merged**
