### PR TITLE
Distinguish Arduino from other ttyUSB devices

### PR DESCRIPTION
**Pull request by pazeshun**
Using the knowledge in https://unix.stackexchange.com/questions/105144/udev-rule-for-assigning-known-symlinks-for-identical-usb-serial-devices

### CODE REVIEW

**Comment by pazeshun** [comment]
```
$ ls -l /dev/r_dxhub 
lrwxrwxrwx 1 root root 7  6月 13 17:40 /dev/r_dxhub -> ttyUSB1
$ ls -l /dev/arduino0 
lrwxrwxrwx 1 root root 7  6月 13 17:40 /dev/arduino0 -> ttyUSB0
$ ls -l /dev/arduino1 
lrwxrwxrwx 1 root root 7  6月 13 17:40 /dev/arduino1 -> ttyUSB2
```

**Comment by pazeshun** [comment]
Tested on sheeta with baxter and gripper-v6
```
$ ls -l /dev/ttyUSB*
crw-rw-rw- 1 root dialout 188, 0 Jun 15 11:01 /dev/ttyUSB0
crw-rw-rw- 1 root dialout 188, 1 Jun 15 11:01 /dev/ttyUSB1
crw-rw-rw- 1 root dialout 188, 2 Jun 15 11:01 /dev/ttyUSB2
crw-rw-rw- 1 root dialout 188, 3 Jun 15 11:03 /dev/ttyUSB3
$ ls -l /dev/arduino*
lrwxrwxrwx 1 root root 7 Jun 15 11:01 /dev/arduino0 -> ttyUSB0
lrwxrwxrwx 1 root root 7 Jun 15 11:01 /dev/arduino1 -> ttyUSB1
lrwxrwxrwx 1 root root 7 Jun 15 11:03 /dev/arduino2 -> ttyUSB3
$ ls -l /dev/r_dxhub 
lrwxrwxrwx 1 root root 7 Jun 15 11:01 /dev/r_dxhub -> ttyUSB2
```

**Comment by pazeshun** [comment]
No more WIP

**Comment by pazeshun** [comment]
Rebase origin/master

**Comment by pazeshun** [comment]
@wkentaro Can you review this?

**Comment by wkentaro** [comment]
I think you can add `create_udev_rules` executable on this PR.

**Comment by pazeshun** [comment]
> I think you can add create_udev_rules executable on this PR.

Sorry for late. I added.
I'll test this tomorrow.

**Comment by pazeshun** [comment]
Tested on sheeta
No more WIP
@wkentaro Can you review this again?

**Pull request merged**
