### PR TITLE
add inertia tag in both gripper.urdf.xacro

### LINKED ISSUE #1893: gripper_pad is not loaded to gazebo
Require https://github.com/start-jsk/jsk_apc/pull/1892 and https://github.com/RethinkRobotics/baxter_simulator/pull/88

Gazebo simulator cannot load gripper pad.

gazebo_apc_tuck
gazebo_gripper_pad

### PR DESCRIPTION
**Pull request by knorth55**
Fix #1893 

Thanks to @mmurooka
This PR solves problem to load robot model in gazebo.
baxter_gazebo_load

### CODE REVIEW

**Comment by mmurooka** [comment]
@knorth55 , png link in https://github.com/start-jsk/jsk_apc/pull/1975#issue-193775250 is not correct?

**Comment by knorth55** [comment]
thank you @mmurooka

**Comment by pazeshun** [comment]
Thank you!
Sorry for my late work…
+1

**Comment by knorth55** [comment]
Updated: add `material` tag for gazebo

baxter_gazebo_load

**Comment by pazeshun** [comment]
+1

**Pull request merged**
