### PR TITLE
[WIP] Allow moveit is not set

### PR DESCRIPTION
**Pull request by pazeshun**

### CODE REVIEW

**Comment by knorth55** [comment]
can you add it in `lib/pick-interface.l`?
like 
```
(when (boundp `*co*) (send *ti* :add-shelf-scene))
```

**Comment by knorth55** [comment]
Or I can do it by myself

**Comment by pazeshun** [comment]
> can you add it in lib/pick-interface.l?
> like
> 
> (when (boundp `*co*) (send *ti* :add-shelf-scene))

Ok, I'll do this.

**Comment by knorth55** [comment]
move to #2149

**Pull request closed without merging**
