### PR TITLE
Speed up finger motion in suction

### PR DESCRIPTION
**Pull request by pazeshun**
I haven't tested in real robot.

### CODE REVIEW

**Comment by k-okada** [comment]
```

[jsk_arc2017_baxter:make] rostest log file is in /workspace/start-jsk/jsk_apc/log/rostest-926aeb6d9d9b-12713.log
[jsk_arc2017_baxter:make] -- run_tests.py: verify result "/workspace/ros/ws_jsk_apc/build/jsk_arc2017_baxter/test_results/jsk_arc2017_baxter/rostest-test_test_stow_state_server.xml"
[jsk_arc2017_baxter:make] make[3]: Leaving directory `/workspace/ros/ws_jsk_apc/build/jsk_arc2017_baxter'
[jsk_arc2017_baxter:make] /usr/bin/cmake -E cmake_progress_report /workspace/ros/ws_jsk_apc/build/jsk_arc2017_baxter/CMakeFiles 
[jsk_arc2017_baxter:make] Built target _run_tests_jsk_arc2017_baxter_rostest_test_test_stow_state_server.test
[jsk_arc2017_baxter:make] Call Stack (max depth: 20):
[jsk_arc2017_baxter:make]   0: at (send msg :contents)
[jsk_arc2017_baxter:make]   1: at (mapcar #'(lambda (content) (cons (str2symbol (send content :bin)) (send content :items))) (send msg :contents))
[jsk_arc2017_baxter:make]   2: at (setq bin-contents (mapcar #'(lambda (content) (cons (str2symbol (send content :bin)) (send content :items))) (send msg :contents)))
[jsk_arc2017_baxter:make]   3: at (let (target-bins postponed-bins msg) (setq msg (one-shot-subscribe "/json_saver/output/bin_contents" jsk_arc2017_common::contentarray :timeout 10000 :after-stamp stamp)) (setq bin-contents (mapcar #'(lambda (content) (cons (str2symbol (send content :bin)) (send content :items))) (send msg :contents))) (setq target-bins (remove nil (mapcar #'(lambda (order) (let ((item (send order :item)) (bin (str2symbol (send order :bin)))) (when (find item (cdr (assoc bin bin-contents)) :test #'string=) (unless (or (find item (gethash bin finished-objects-) :test #'string=) (find item (gethash bin postponed-objects-) :test #'string=)) bin)))) orders-))) (when target-bins (return-from :get-next-target-bin (elt target-bins (random (length target-bins))))) (setq postponed-bins (remove nil (mapcar #'(lambda (order) (let ((item (send order :item)) (bin (str2symbol (send order :bin)))) (when (find item (cdr (assoc bin bin-contents)) :test #'string=) (unless (find item (gethash bin finished-objects-) :test #'string=) bin)))) orders-))) (when postponed-bins (return-from :get-next-target-bin (elt postponed-bins (random (length postponed-bins))))) nil)
[jsk_arc2017_baxter:make]   4: at (send *ti* :get-next-target-bin :rarm)
[jsk_arc2017_baxter:make]   5: at (find (send *ti* :get-next-target-bin :rarm) (list :a :c))
[jsk_arc2017_baxter:make]   6: at (let* (failure (ret (find (send *ti* :get-next-target-bin :rarm) (list :a :c)))) (if (not ret) (send *unit-test* :increment-failure '(find (send *ti* :get-next-target-bin :rarm) (list :a :c)) (format nil (format nil "failed to get-next-target-bin: ~a" (symbol2str (send *ti* :get-next-target-bin :rarm)))) (escape-xml-string (subseq (send *error-output* :buffer) 0 (or (position 0 (send *error-output* :buffer)) (length (send *error-output* :buffer))))))))
[jsk_arc2017_baxter:make]   7: at (funcall func)
[jsk_arc2017_baxter:make]   8: at (funcall func)
[jsk_arc2017_baxter:make]   9: at (let ((func (symbol-function func-sym)) tm) (send *unit-test* :init-result func-sym) (format t "TEST-NAME: ~A~%" func-sym) (format t "  now testing...~%") (send *unit-test* :increment-test func-sym) (setq tm (instance mtimer :init)) (send tm :start) (funcall func) (send *unit-test* :set-time-to-current-result (send tm :stop)))
[jsk_arc2017_baxter:make]   10: at (run-test u)
[jsk_arc2017_baxter:make]   11: at (while #:dolist13535 (setq u (pop #:dolist13535)) (run-test u))
[jsk_arc2017_baxter:make]   12: at (let ((u nil) (#:dolist13535 (send *unit-test* :functions))) nil (while #:dolist13535 (setq u (pop #:dolist13535)) (run-test u)) nil)
[jsk_arc2017_baxter:make]   13: at (dolist (u (send *unit-test* :functions)) (run-test u))
[jsk_arc2017_baxter:make]   14: at (run-all-tests)
[jsk_arc2017_baxter:make] /opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: cannot find method :contents in (send msg :contents), exitting...
[jsk_arc2017_baxter:make] [ERROR] test (send msg :contents) failed ... (cannot find method 40).
[jsk_arc2017_baxter:make] testtest_pick_arc_interface ... ok
[jsk_arc2017_baxter:make] 
[jsk_arc2017_baxter:make] [ROSTEST]-----------------------------------------------------------------------
[jsk_arc2017_baxter:make] 
[jsk_arc2017_baxter:make] [jsk_arc2017_baxter.rosunit-test_pick_arc_interface/all-test][FAILURE]----------
[jsk_arc2017_baxter:make] Test:(send msg :contents)
[jsk_arc2017_baxter:make] Trace:40
[jsk_arc2017_baxter:make] Message:"cannot find method"
[jsk_arc2017_baxter:make] --------------------------------------------------------------------------------
[jsk_arc2017_baxter:make] 
```

**Comment by wkentaro** [comment]
I will rebase

**Comment by k-okada** [comment]
filed log -> https://api.travis-ci.org/jobs/257524398/log.txt?deansi=true and restarted travis

**Comment by knorth55** [comment]
i now why it fails, I'm fixing now.

**Pull request merged**
