### PR TITLE
[Depends on #1655] Add gripper-v3 model

### PR DESCRIPTION
**Pull request by pazeshun**
Make URDF model including gripper-v3 on left arm:
screenshot from 2016-06-10 01 21 29
Visual model of gripper-v3:
screenshot from 2016-06-10 01 22 30
Collision model of gripper-v3:
screenshot from 2016-06-10 01 23 58

### CODE REVIEW

**Comment by pazeshun** [comment]
Also, make Eus robot model including gripper-v3:
screenshot from 2016-06-10 01 29 13
We can rotate gripper properly on simulation:
screenshot from 2016-06-10 01 29 47
end-coords of larm is proper:
screenshot from 2016-06-10 01 56 06

**Comment by pazeshun** [comment]
Without #1655 , this won't work in real robot.

**Comment by ban-masa** [comment]
I think there is no mistake, but I'm not sure about xacro...
+1

**Comment by pazeshun** [comment]
Tested in real robot with #1655 , #1656, #1663. No more WIP.
Please merge this.

**Pull request merged**
