### PR TITLE
baxter-interface.l : set joint-states-queue-size 2 for gripper and body

### PR DESCRIPTION
**Pull request by k-okada**
this requires https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/229

tested with 
```
(load "package://jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l")
(load "package://jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/util.l")

(unless (boundp '*baxter*)
  (setq *baxter* (instance jsk_2016_01_baxter_apc::baxter-robot :init)))
(defun setup (&optional (ctype :default-controller))
  (jsk_2016_01_baxter_apc::baxter-init :ctype ctype)
  (send *ri* :gripper-servo-on)
  (send *ri* :angle-vector (send *baxter* :fold-pose-back))
  (send *ri* :wait-interpolation)
  (objects (list *baxter*))

  (setq av1 #f(0.0 97.4707 -2.39502 -94.5483 134.67 91.4062 8.70117 0.0 -5.40301 55.9257 117.063 72.4793 -62.7243 -7.73117 -87.322 90.0))
  (setq av2 #f(0.0 97.4707 -2.39502 -94.5483 134.67 91.4062 8.70117 0.0 -8.22871 40.7953 92.2281 64.6958 -80.3615 -21.3969 -46.1696 90.0))
  )

;;;
(defun send-av1 ()
  (send *baxter* :angle-vector av1)
  (send *baxter* :rarm :shoulder-y :joint-angle -20)
  (send *ri* :angle-vector (send *baxter* :angle-vector) 5000)
  )

(defun send-av2 ()
  (send *baxter* :angle-vector av2)
  (send *baxter* :rarm :shoulder-y :joint-angle -20)
  (send *ri* :angle-vector (send *baxter* :angle-vector) 1000)
  )

(defun send-avs ()
  (send-av1)
  (print 'wait!!)
  (send *ri* :wait-interpolation)
  (send-av2)
  (print 'sleep!!)
  ;;(unix:sleep 1)
  ;;(ros::duration-sleep 1)
  (ros::rate 1)
  (ros::sleep)
  )

(setup)
(do-until-key (send-avs))
```

### CODE REVIEW

**Comment by pazeshun** [comment]
I think we have to merge this after jsk-ros-pkg/jsk_pr2eus#229 is released.

**Comment by k-okada** [comment]
I think it's ok to merge, just ignore keyword until pr2eus is rereleased

2016年5月25日水曜日、pazeshun<notifications@github.com>さんは書きました:

> I think we have to merge this after jsk-ros-pkg/jsk_pr2eus#229
> <https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/229> is released.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/pull/1537#issuecomment-221551608>
>


-- 
--
◉ Kei Okada

**Comment by pazeshun** [comment]
I overlooked https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L101
@k-okada Thank you.
+1

**Comment by k-okada** [comment]
0.3.2 of pr2eus was released http://repositories.ros.org/status_page/ros_indigo_default.html?q=pr2eus

**Comment by pazeshun** [comment]
Thank you. I'll update on sheeta.

**Comment by pazeshun** [comment]
Updated pr2eus on sheeta.

**Pull request merged**
