### PR TITLE
[WIP] scipts to gather data

### PR DESCRIPTION
**Pull request by yuyu2172**
# TODOs
1. ~~change object set from command line~~
2. ~~save dist image as well (skipping)~~
3. ~~make a GUI that lets you start recording~~
4. ~~make json for collecting dataset (from 20 objects pick 3 without duplicate?)~~

### CODE REVIEW

**Comment by knorth55** [comment]
kinect_torsoの位置合わせだけ先に別にPRつくってもらえますか？

**Comment by wkentaro** [comment]
> kinect_torsoの位置合わせだけ先に別にPRつくってもらえますか？

Its done in https://github.com/start-jsk/jsk_apc/pull/1686

**Comment by knorth55** [comment]
i got it  thank you

**Comment by yuyu2172** [comment]
#1713 #1712

**Pull request closed without merging**
