### PR TITLE
Data collection program for segmentation in bin

### PR DESCRIPTION
**Pull request by wkentaro**
Data is collected here: https://drive.google.com/open?id=0B9P1L--7Wd2vQ0NfVmNTS1pnemM

### CODE REVIEW

**Comment by yuyu2172** [comment]
Subscribe to bininfo.

**Comment by wkentaro** [comment]
> Also, is the data saving format consistent with the current convention?

NO, because this is only for FCN.

**Comment by wkentaro** [comment]
> I think that it is not burdensome to set json when launching data collecting script.

Putting objects in bin according to json file takes time.

**Comment by wkentaro** [comment]
It is annotated like below:

image
label
label_viz

**Comment by yuyu2172** [comment]
Automatic collection is nice

**Pull request merged**
