### PR TITLE
[WIP] Add InHandRecogntionNode for unknown objects

### PR DESCRIPTION
**Pull request by yuyu2172**
Related https://github.com/start-jsk/jsk_apc/issues/2187
Close https://github.com/start-jsk/jsk_apc/issues/2037

- [ ] Tests
- [ ] Is this the right place to put code?
- [ ] Extra dependencies

### CODE REVIEW

**Comment by wkentaro** [comment]
@yuyu2172 It seems better if you put the template maching node to jsk_recognition package. Any idea?  cc @knorth55

**Comment by yuyu2172** [comment]
We don't know if the performance of this system is sufficiently good enough for ARC.
I think it is better to first make sure that this system works before considering to merge them to the upstream repository.

**Comment by wkentaro** [comment]
You can test it using apc2016 objects, and send PR with that results.

**Comment by yuyu2172** [comment]
download

More results can be found in https://github.com/yuyu2172/arc/blob/master/notebooks/retrieval_prediction_example.ipynb (private repo).

**Comment by yuyu2172** [comment]
Closing
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2171

**Pull request closed without merging**
