### PR TITLE
[jsk_2015_05_baxter_apc | jsk_2016_01_baxter_apc] fix cmakelist depends path into full path

### PR DESCRIPTION
**Pull request by knorth55**

### CODE REVIEW

**Comment by wkentaro** [comment]
Why is this needed?

**Comment by knorth55** [comment]
this is correct syntax

**Comment by wkentaro** [comment]
why is it correct?

**Comment by knorth55** [comment]
in cmake documentation, i read that absolute path is recommended

**Comment by wkentaro** [comment]
> in cmake documentation, i read that absolute path is recommended

Where is it?

**Comment by wkentaro** [comment]
This can be merged for safety.

**Pull request merged**
