### PR TITLE
add sleep in calib_required_controller

### PR DESCRIPTION
**Pull request by knorth55**
@pazeshun 
we found this error with softhand.
original commit is here https://github.com/knorth55/softhand_ros/commit/e196a45ea0d25894f1c09bcbdcc42942abf113f4

### CODE REVIEW

**Comment by pazeshun** [comment]
We will continuously check if this is really required through @knorth55 's use case.

**Comment by knorth55** [comment]
can you review agian this PR?
I will merge this if OK.

**Comment by pazeshun** [comment]
Sorry, could you add the same change to https://github.com/start-jsk/jsk_apc/blob/master/demos/sphand_ros/sphand_driver/src/sphand_driver/calib_required_joint_controller.py?

**Comment by knorth55** [comment]
I added

**Review by pazeshun — APPROVED** [review]
Thank you!

**Pull request merged**
