### PR TITLE
[jsk_2016_01_baxter_apc] Fix robot self filter for new right gripper

### LINKED ISSUE #1456: [jsk_apc_2016_baxter_apc] robot self filter does not work properly
Because `robot_description` is modified, `robot_self_filter` does not work properly so that it failed to verify object in hand.
Upper: before self filtered
Lower: after self filtered 
before_filter
after_filter

### PR DESCRIPTION
**Pull request by pazeshun**
Fixes #1456 
Add robot self filter for apc2016 robot model like #1458 
Also, change collision meshes of `right_gripper_base` and `right_gripper_vacuum_pad_base` from STL data to URDF boxes and cylinders.
Visual links
screenshot from 2016-05-16 11 21 55
Visual and collision links
screenshot from 2016-05-16 11 21 32
I'll test this in real robot.

### CODE REVIEW

**Comment by pazeshun** [comment]
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```
travis coudn't connect to jenkins

**Comment by pazeshun** [comment]
I tested in real robot.
screenshot from 2016-05-16 16 05 17
Now robot_self_filter works.

**Comment by pazeshun** [comment]
Around `right_gripper_vacuum_pad`, robot_self_filter didn't work.
screenshot from 2016-05-16 16 24 12
screenshot from 2016-05-16 16 24 22
I'll debug.

**Comment by pazeshun** [comment]
I changed collision mesh of `right_gripper_vacuum_pad` from STL data to URDF cylinder. Then robot_self_filter works properly.
screenshot from 2016-05-16 17 03 36
Now robot_self_filter works properly with this PR.

**Comment by pazeshun** [comment]
@knorth55 Please test this on master branch

**Comment by knorth55** [comment]
ok, thank you

**Pull request merged**
